baseurl = "/"
title = "Articles"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Articles"
    description = "A Collection of Writings about Software Engineering"
    github = "https://github.com/carlosrodfern"
    gitlab = "https://gitlab.com/carlosrodfern"
    linkedin = "https://www.linkedin.com/in/carlosrodfern/"
    email = "carlosrodrifernandez@gmail.com"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
